name: PR Quality Checks

on:
  pull_request:
    branches:
      - develop
  workflow_dispatch: # Permite acionamento manual

jobs:
  quality-checks:
    runs-on: ubuntu-latest

    steps:
      - name:  Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH
        shell: bash

      - name: Install dependencies
        run: |
          uv venv
          source .venv/bin/activate
          uv pip install -e ".[dev]"
        shell: bash

      - name: Run Linters (Ruff and Black)
        run: |
          source .venv/bin/activate
          make lint
        shell: bash

      - name: Run Type Checker (MyPy)
        run: |
          source .venv/bin/activate
          make type-check
        shell: bash

      - name: Run Tests (Pytest)
        run: |
          source .venv/bin/activate
          make test
        shell: bash